/* =============================================================================
   Design Tokens — TypeScript Constants
   AUTO-GENERATED by scripts/build-tokens.mjs — do not edit manually.
   Re-generate: node scripts/build-tokens.mjs
   ============================================================================= */

export const tokens = {
  colorPrimitiveNeutral0: { cssVar: '--color-primitive-neutral-0', value: '#ffffff' },
  /** Lightest background surface */
  colorPrimitiveNeutral50: { cssVar: '--color-primitive-neutral-50', value: '#f7f7f6' },
  /** Off-white page background */
  colorPrimitiveNeutral100: { cssVar: '--color-primitive-neutral-100', value: '#f5f5f0' },
  colorPrimitiveNeutral150: { cssVar: '--color-primitive-neutral-150', value: '#f6f6f5' },
  /** Subtle border / divider */
  colorPrimitiveNeutral200: { cssVar: '--color-primitive-neutral-200', value: '#ccd1c7' },
  /** Muted border */
  colorPrimitiveNeutral300: { cssVar: '--color-primitive-neutral-300', value: '#afb4aa' },
  /** Placeholder / disabled text */
  colorPrimitiveNeutral400: { cssVar: '--color-primitive-neutral-400', value: '#999999' },
  /** Secondary text */
  colorPrimitiveNeutral500: { cssVar: '--color-primitive-neutral-500', value: '#959595' },
  /** Muted foreground */
  colorPrimitiveNeutral600: { cssVar: '--color-primitive-neutral-600', value: '#5e6459' },
  /** Medium dark surface */
  colorPrimitiveNeutral700: { cssVar: '--color-primitive-neutral-700', value: '#404540' },
  /** Dark surface */
  colorPrimitiveNeutral800: { cssVar: '--color-primitive-neutral-800', value: '#2c2c2c' },
  /** Dark surface variant */
  colorPrimitiveNeutral850: { cssVar: '--color-primitive-neutral-850', value: '#2b2e2b' },
  /** Near-black surface */
  colorPrimitiveNeutral900: { cssVar: '--color-primitive-neutral-900', value: '#1f1b1b' },
  /** Primary foreground */
  colorPrimitiveNeutral950: { cssVar: '--color-primitive-neutral-950', value: '#141414' },
  colorPrimitiveNeutral1000: { cssVar: '--color-primitive-neutral-1000', value: '#000000' },
  /** Teal mid */
  colorPrimitiveTeal300: { cssVar: '--color-primitive-teal-300', value: '#3cc8c8' },
  /** Brand teal — primary accent */
  colorPrimitiveTeal400: { cssVar: '--color-primitive-teal-400', value: '#1ce3af' },
  /** Secondary accent */
  colorPrimitivePurple400: { cssVar: '--color-primitive-purple-400', value: '#9747ff' },
  colorPrimitivePurple500: { cssVar: '--color-primitive-purple-500', value: '#6e0070' },
  colorPrimitivePurple600: { cssVar: '--color-primitive-purple-600', value: '#4b004f' },
  /** Highlight */
  colorPrimitiveYellow400: { cssVar: '--color-primitive-yellow-400', value: '#fad91f' },
  colorPrimitiveYellow500: { cssVar: '--color-primitive-yellow-500', value: '#fff200' },
  colorPrimitiveOrange400: { cssVar: '--color-primitive-orange-400', value: '#ff8a00' },
  colorPrimitiveOrange500: { cssVar: '--color-primitive-orange-500', value: '#da720e' },
  colorPrimitiveRed400: { cssVar: '--color-primitive-red-400', value: '#f04654' },
  colorPrimitiveRed500: { cssVar: '--color-primitive-red-500', value: '#c71826' },
  colorPrimitiveGreen400: { cssVar: '--color-primitive-green-400', value: '#18a24a' },
  colorPrimitiveGreen500: { cssVar: '--color-primitive-green-500', value: '#157937' },
  colorSemanticBackgroundDefault: { cssVar: '--color-semantic-background-default', value: '#f5f5f0' },
  colorSemanticBackgroundSubtle: { cssVar: '--color-semantic-background-subtle', value: '#f7f7f6' },
  colorSemanticBackgroundMuted: { cssVar: '--color-semantic-background-muted', value: '#f6f6f5' },
  colorSemanticBackgroundInverted: { cssVar: '--color-semantic-background-inverted', value: '#141414' },
  colorSemanticForegroundDefault: { cssVar: '--color-semantic-foreground-default', value: '#141414' },
  colorSemanticForegroundMuted: { cssVar: '--color-semantic-foreground-muted', value: '#5e6459' },
  colorSemanticForegroundSubtle: { cssVar: '--color-semantic-foreground-subtle', value: '#959595' },
  colorSemanticForegroundInverted: { cssVar: '--color-semantic-foreground-inverted', value: '#ffffff' },
  colorSemanticBorderDefault: { cssVar: '--color-semantic-border-default', value: '#ccd1c7' },
  colorSemanticBorderStrong: { cssVar: '--color-semantic-border-strong', value: '#afb4aa' },
  colorSemanticBrandDefault: { cssVar: '--color-semantic-brand-default', value: '#1ce3af' },
  colorSemanticBrandHover: { cssVar: '--color-semantic-brand-hover', value: '#3cc8c8' },
  colorSemanticBrandSubtle: { cssVar: '--color-semantic-brand-subtle', value: '#e6fdf8' },
  colorSemanticBrandForeground: { cssVar: '--color-semantic-brand-foreground', value: '#141414' },
  colorSemanticAccentDefault: { cssVar: '--color-semantic-accent-default', value: '#9747ff' },
  colorSemanticAccentForeground: { cssVar: '--color-semantic-accent-foreground', value: '#ffffff' },
  typographyFontFamilyDisplay: { cssVar: '--typography-fontFamily-display', value: '\'Bricolage Grotesque\', ui-sans-serif, sans-serif' },
  typographyFontFamilyBody: { cssVar: '--typography-fontFamily-body', value: 'Inter, ui-sans-serif, system-ui, sans-serif' },
  typographyFontFamilyLabel: { cssVar: '--typography-fontFamily-label', value: '\'Archivo Narrow\', ui-sans-serif, sans-serif' },
  typographyFontFamilyMono: { cssVar: '--typography-fontFamily-mono', value: '\'JetBrains Mono\', ui-monospace, monospace' },
  /** 12px */
  typographyFontSizeXs: { cssVar: '--typography-fontSize-xs', value: '0.75rem' },
  /** 14px */
  typographyFontSizeSm: { cssVar: '--typography-fontSize-sm', value: '0.875rem' },
  /** 16px */
  typographyFontSizeBase: { cssVar: '--typography-fontSize-base', value: '1rem' },
  /** 24px */
  typographyFontSizeLg: { cssVar: '--typography-fontSize-lg', value: '1.5rem' },
  /** 40px */
  typographyFontSizeXl: { cssVar: '--typography-fontSize-xl', value: '2.5rem' },
  /** 56px */
  typographyFontSize2xl: { cssVar: '--typography-fontSize-2xl', value: '3.5rem' },
  /** 64px */
  typographyFontSize3xl: { cssVar: '--typography-fontSize-3xl', value: '4rem' },
  /** 120px */
  typographyFontSize4xl: { cssVar: '--typography-fontSize-4xl', value: '7.5rem' },
  /** 180px */
  typographyFontSize5xl: { cssVar: '--typography-fontSize-5xl', value: '11.25rem' },
  typographyFontWeightRegular: { cssVar: '--typography-fontWeight-regular', value: '400' },
  typographyFontWeightMedium: { cssVar: '--typography-fontWeight-medium', value: '500' },
  typographyFontWeightSemibold: { cssVar: '--typography-fontWeight-semibold', value: '600' },
  typographyFontWeightExtrabold: { cssVar: '--typography-fontWeight-extrabold', value: '800' },
  typographyLineHeightNone: { cssVar: '--typography-lineHeight-none', value: '1' },
  typographyLineHeightTight: { cssVar: '--typography-lineHeight-tight', value: '1.1' },
  typographyLineHeightSnug: { cssVar: '--typography-lineHeight-snug', value: '1.2' },
  typographyLineHeightNormal: { cssVar: '--typography-lineHeight-normal', value: '1.5' },
  typographyLineHeightRelaxed: { cssVar: '--typography-lineHeight-relaxed', value: '1.625' },
  typographyLetterSpacingTighter: { cssVar: '--typography-letterSpacing-tighter', value: '-0.01em' },
  typographyLetterSpacingTight: { cssVar: '--typography-letterSpacing-tight', value: '-0.005em' },
  typographyLetterSpacingNormal: { cssVar: '--typography-letterSpacing-normal', value: '0em' },
  typographyLetterSpacingWide: { cssVar: '--typography-letterSpacing-wide', value: '0.04em' },
  typographyLetterSpacingWider: { cssVar: '--typography-letterSpacing-wider', value: '0.06em' },
  spacing0: { cssVar: '--spacing-0', value: '0px' },
  /** 4px */
  spacing1: { cssVar: '--spacing-1', value: '0.25rem' },
  /** 8px */
  spacing2: { cssVar: '--spacing-2', value: '0.5rem' },
  /** 12px */
  spacing3: { cssVar: '--spacing-3', value: '0.75rem' },
  /** 16px */
  spacing4: { cssVar: '--spacing-4', value: '1rem' },
  /** 20px */
  spacing5: { cssVar: '--spacing-5', value: '1.25rem' },
  /** 24px */
  spacing6: { cssVar: '--spacing-6', value: '1.5rem' },
  /** 32px */
  spacing8: { cssVar: '--spacing-8', value: '2rem' },
  /** 40px */
  spacing10: { cssVar: '--spacing-10', value: '2.5rem' },
  /** 48px */
  spacing12: { cssVar: '--spacing-12', value: '3rem' },
  /** 60px */
  spacing15: { cssVar: '--spacing-15', value: '3.75rem' },
  /** 64px */
  spacing16: { cssVar: '--spacing-16', value: '4rem' },
  /** 80px */
  spacing20: { cssVar: '--spacing-20', value: '5rem' },
  /** 120px */
  spacing30: { cssVar: '--spacing-30', value: '7.5rem' },
  /** 180px */
  spacing45: { cssVar: '--spacing-45', value: '11.25rem' },
  spacingPx: { cssVar: '--spacing-px', value: '1px' },
  /** 6px */
  spacing1_5: { cssVar: '--spacing-1-5', value: '0.375rem' },
  /** 10px */
  spacing2_5: { cssVar: '--spacing-2-5', value: '0.625rem' },
  borderRadiusNone: { cssVar: '--borderRadius-none', value: '0px' },
  /** 2px */
  borderRadiusXs: { cssVar: '--borderRadius-xs', value: '0.125rem' },
  /** 6px — tags, chips */
  borderRadiusSm: { cssVar: '--borderRadius-sm', value: '0.375rem' },
  /** 13px — cards */
  borderRadiusMd: { cssVar: '--borderRadius-md', value: '0.8125rem' },
  /** 16px — panels */
  borderRadiusLg: { cssVar: '--borderRadius-lg', value: '1rem' },
  /** 32px — large cards */
  borderRadiusXl: { cssVar: '--borderRadius-xl', value: '2rem' },
  /** Pills, avatars */
  borderRadiusFull: { cssVar: '--borderRadius-full', value: '999px' },
  shadowNone: { cssVar: '--shadow-none', value: 'none' },
  shadowSm: { cssVar: '--shadow-sm', value: '0 1px 2px 0 rgb(20 20 20 / 0.06)' },
  shadowBase: { cssVar: '--shadow-base', value: '0 2px 8px 0 rgb(20 20 20 / 0.08), 0 1px 2px 0 rgb(20 20 20 / 0.04)' },
  shadowMd: { cssVar: '--shadow-md', value: '0 4px 16px 0 rgb(20 20 20 / 0.10), 0 2px 4px 0 rgb(20 20 20 / 0.06)' },
  shadowLg: { cssVar: '--shadow-lg', value: '0 8px 32px 0 rgb(20 20 20 / 0.12), 0 4px 8px 0 rgb(20 20 20 / 0.06)' },
  shadowXl: { cssVar: '--shadow-xl', value: '0 16px 48px 0 rgb(20 20 20 / 0.14), 0 8px 16px 0 rgb(20 20 20 / 0.08)' },
  motionDurationInstant: { cssVar: '--motion-duration-instant', value: '0ms' },
  motionDurationFast: { cssVar: '--motion-duration-fast', value: '100ms' },
  motionDurationNormal: { cssVar: '--motion-duration-normal', value: '200ms' },
  motionDurationSlow: { cssVar: '--motion-duration-slow', value: '350ms' },
  motionDurationSlower: { cssVar: '--motion-duration-slower', value: '500ms' },
  motionEasingLinear: { cssVar: '--motion-easing-linear', value: 'cubic-bezier(0, 0, 1, 1)' },
  motionEasingEase: { cssVar: '--motion-easing-ease', value: 'cubic-bezier(0.25, 0.1, 0.25, 1)' },
  motionEasingEase_in: { cssVar: '--motion-easing-ease-in', value: 'cubic-bezier(0.4, 0, 1, 1)' },
  motionEasingEase_out: { cssVar: '--motion-easing-ease-out', value: 'cubic-bezier(0, 0, 0.2, 1)' },
  motionEasingEase_in_out: { cssVar: '--motion-easing-ease-in-out', value: 'cubic-bezier(0.4, 0, 0.2, 1)' },
  motionEasingSpring: { cssVar: '--motion-easing-spring', value: 'cubic-bezier(0.34, 1.56, 0.64, 1)' },
  zIndexBase: { cssVar: '--zIndex-base', value: '0' },
  zIndexRaised: { cssVar: '--zIndex-raised', value: '10' },
  zIndexOverlay: { cssVar: '--zIndex-overlay', value: '20' },
  zIndexModal: { cssVar: '--zIndex-modal', value: '30' },
  zIndexToast: { cssVar: '--zIndex-toast', value: '40' },
  zIndexTooltip: { cssVar: '--zIndex-tooltip', value: '50' },
} as const;

export type TokenKey = keyof typeof tokens;

/** Returns the CSS variable reference string for use in inline styles */
export function tokenVar(key: TokenKey): string {
  return `var(${tokens[key].cssVar})`;
}
