/**
 * Token build script
 *
 * Reads tokens/tokens.json and generates:
 *   - tokens/tokens.css  (CSS custom properties, light + dark)
 *   - tokens/tokens.ts   (TypeScript constants for use in JS logic)
 *
 * Run: node scripts/build-tokens.mjs
 *
 * When Figma MCP is connected, update tokens.json first, then re-run this script.
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'tokens/tokens.json'), 'utf8'));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Convert a nested key path like ['color','semantic','background','default'] → CSS var name */
function toCssVar(parts) {
  return '--' + parts.join('-').replace(/\./g, '-');
}

/** Resolve a W3C reference like "{color.primitive.neutral.0}" to its raw value */
function resolveRef(value, root) {
  if (typeof value !== 'string' || !value.startsWith('{')) return value;
  const path = value.slice(1, -1).split('.');
  let node = root;
  for (const key of path) {
    node = node?.[key];
  }
  return node?.['$value'] ?? value;
}

/** Walk the token tree and collect leaf nodes with their path */
function collectTokens(obj, path = [], collected = []) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    if (typeof val === 'object' && val !== null && !Array.isArray(val)) {
      if ('$value' in val) {
        collected.push({
          path: [...path, key],
          value: val['$value'],
          description: val['$description'],
        });
      } else {
        collectTokens(val, [...path, key], collected);
      }
    }
  }
  return collected;
}

// ---------------------------------------------------------------------------
// Collect all tokens
// ---------------------------------------------------------------------------

const allTokens = collectTokens(tokens);

// Separate dark semantic tokens from the rest
const lightTokens = allTokens.filter((t) => !t.path.includes('dark'));
const darkTokens = allTokens
  .filter((t) => t.path.includes('dark'))
  .map((t) => {
    // Strip 'dark' segment from path to produce the same var name as light
    const cleanPath = t.path.filter((p) => p !== 'dark');
    return { ...t, path: cleanPath };
  });

// ---------------------------------------------------------------------------
// Resolve references
// ---------------------------------------------------------------------------

function resolveValue(value) {
  const resolved = resolveRef(value, tokens);
  // If still a reference (nested), resolve again
  if (typeof resolved === 'string' && resolved.startsWith('{')) {
    return resolveRef(resolved, tokens);
  }
  if (Array.isArray(resolved)) {
    // cubicBezier
    return `cubic-bezier(${resolved.join(', ')})`;
  }
  return resolved;
}

// ---------------------------------------------------------------------------
// Generate CSS
// ---------------------------------------------------------------------------

function tokensToCssVars(tokenList) {
  return tokenList
    .map(({ path, value }) => {
      const varName = toCssVar(path);
      const resolved = resolveValue(value);
      return `  ${varName}: ${resolved};`;
    })
    .join('\n');
}

const cssContent = `/* =============================================================================
   Design Tokens — CSS Custom Properties
   AUTO-GENERATED by scripts/build-tokens.mjs — do not edit manually.
   Re-generate: node scripts/build-tokens.mjs
   ============================================================================= */

:root {
${tokensToCssVars(lightTokens)}
}

[data-theme="dark"] {
${tokensToCssVars(darkTokens)}
}
`;

writeFileSync(resolve(root, 'tokens/tokens.css'), cssContent, 'utf8');
console.log('✓ tokens/tokens.css written');

// ---------------------------------------------------------------------------
// Generate TypeScript
// ---------------------------------------------------------------------------

function toTsKey(parts) {
  // Convert ['color', 'semantic', 'background', 'default'] → 'colorSemanticBackgroundDefault'
  return parts
    .map((p, i) => {
      const clean = p.replace(/[^a-zA-Z0-9]/g, '_');
      return i === 0 ? clean : clean.charAt(0).toUpperCase() + clean.slice(1);
    })
    .join('');
}

const tsEntries = lightTokens.map(({ path, value, description }) => {
  const key = toTsKey(path);
  const varName = toCssVar(path);
  const resolved = String(resolveValue(value)).replace(/'/g, "\\'");
  const comment = description ? `  /** ${description} */\n` : '';
  return `${comment}  ${key}: { cssVar: '${varName}', value: '${resolved}' },`;
});

const tsContent = `/* =============================================================================
   Design Tokens — TypeScript Constants
   AUTO-GENERATED by scripts/build-tokens.mjs — do not edit manually.
   Re-generate: node scripts/build-tokens.mjs
   ============================================================================= */

export const tokens = {
${tsEntries.join('\n')}
} as const;

export type TokenKey = keyof typeof tokens;

/** Returns the CSS variable reference string for use in inline styles */
export function tokenVar(key: TokenKey): string {
  return \`var(\${tokens[key].cssVar})\`;
}
`;

writeFileSync(resolve(root, 'tokens/tokens.ts'), tsContent, 'utf8');
console.log('✓ tokens/tokens.ts written');

console.log(
  `\nTotal tokens: ${lightTokens.length} (light) + ${darkTokens.length} (dark overrides)`,
);
